package cn.thyonline.house.common.pojo;

import java.io.Serializable;
import java.util.Date;

public class House implements Serializable {
    private static final long serialVersionUID = -3758728105821897261L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.id
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.name
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.type
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    private Boolean type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.price
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.images
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    private String images;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.area
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    private Integer area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.beds
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    private Integer beds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.baths
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    private Integer baths;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.rating
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    private Double rating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.remarks
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.properties
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    private String properties;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.floor_plan
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    private String floorPlan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.tags
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    private String tags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.create_time
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.city_id
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.community_id
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    private Integer communityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.address
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.state
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    private Boolean state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.id
     *
     * @return the value of house.id
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.id
     *
     * @param id the value for house.id
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.name
     *
     * @return the value of house.name
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.name
     *
     * @param name the value for house.name
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.type
     *
     * @return the value of house.type
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public Boolean getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.type
     *
     * @param type the value for house.type
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public void setType(Boolean type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.price
     *
     * @return the value of house.price
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.price
     *
     * @param price the value for house.price
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.images
     *
     * @return the value of house.images
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.images
     *
     * @param images the value for house.images
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.area
     *
     * @return the value of house.area
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public Integer getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.area
     *
     * @param area the value for house.area
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public void setArea(Integer area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.beds
     *
     * @return the value of house.beds
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public Integer getBeds() {
        return beds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.beds
     *
     * @param beds the value for house.beds
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public void setBeds(Integer beds) {
        this.beds = beds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.baths
     *
     * @return the value of house.baths
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public Integer getBaths() {
        return baths;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.baths
     *
     * @param baths the value for house.baths
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public void setBaths(Integer baths) {
        this.baths = baths;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.rating
     *
     * @return the value of house.rating
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public Double getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.rating
     *
     * @param rating the value for house.rating
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public void setRating(Double rating) {
        this.rating = rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.remarks
     *
     * @return the value of house.remarks
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.remarks
     *
     * @param remarks the value for house.remarks
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.properties
     *
     * @return the value of house.properties
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public String getProperties() {
        return properties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.properties
     *
     * @param properties the value for house.properties
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public void setProperties(String properties) {
        this.properties = properties == null ? null : properties.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.floor_plan
     *
     * @return the value of house.floor_plan
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public String getFloorPlan() {
        return floorPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.floor_plan
     *
     * @param floorPlan the value for house.floor_plan
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public void setFloorPlan(String floorPlan) {
        this.floorPlan = floorPlan == null ? null : floorPlan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.tags
     *
     * @return the value of house.tags
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.tags
     *
     * @param tags the value for house.tags
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.create_time
     *
     * @return the value of house.create_time
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.create_time
     *
     * @param createTime the value for house.create_time
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.city_id
     *
     * @return the value of house.city_id
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.city_id
     *
     * @param cityId the value for house.city_id
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.community_id
     *
     * @return the value of house.community_id
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public Integer getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.community_id
     *
     * @param communityId the value for house.community_id
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.address
     *
     * @return the value of house.address
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.address
     *
     * @param address the value for house.address
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.state
     *
     * @return the value of house.state
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.state
     *
     * @param state the value for house.state
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    public void setState(Boolean state) {
        this.state = state;
    }
}