package cn.thyonline.house.biz.mapper;

import cn.thyonline.house.common.pojo.HouseUser;
import cn.thyonline.house.common.pojo.HouseUserExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface HouseUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_user
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    int countByExample(HouseUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_user
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    int deleteByExample(HouseUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_user
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_user
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    int insert(HouseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_user
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    int insertSelective(HouseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_user
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    List<HouseUser> selectByExample(HouseUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_user
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    HouseUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_user
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    int updateByExampleSelective(@Param("record") HouseUser record, @Param("example") HouseUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_user
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    int updateByExample(@Param("record") HouseUser record, @Param("example") HouseUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_user
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    int updateByPrimaryKeySelective(HouseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_user
     *
     * @mbggenerated Fri Jun 29 12:17:58 CST 2018
     */
    int updateByPrimaryKey(HouseUser record);
}